version: '3'

services:
  cogserver:
    # See https://github.com/developmentseed/titiler/discussions/387
    platform: linux/amd64
    # enable `image` if you would like to use Docker image from Github package
    #image: ghcr.io/undp-data/cogserver:latest
    build:
      context: .
    # Enable the following volumes if you want to mount source code to Docker
    volumes:
       - "./src/cogserver:/opt/server/cogserver"
    env_file:
      - .env
    ports:
      - 8000:$PORT
